services:
  postgres:
    image: postgres:16.0
    restart: always
    ports:
      - 5555:5432
    environment:
      - POSTGRES_DB=cleanwheel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2525
    healthcheck:
      test: "pg_isready -q -U postgres"

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres/cleanwheel -user=postgres -password=2525 migrate
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - postgres