services:
  postgres:
    image: postgres:16.0
    restart: always
    ports:
      - 5555:5432
    environment:
      - POSTGRES_DB=cleanwheel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2525
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring_net

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres/cleanwheel -user=postgres -password=2525 migrate
    volumes:
      - ./cleanwheel/db/migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - spring_net

  java-app:
    build:
      context: cleanwheel
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cleanwheel
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2525
    networks:
      - spring_net
      - frontend_net

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80" # Mapeia a porta 80 do container para a porta 3000 local
    depends_on:
      - java-app # Certifique-se que o backend esteja rodando antes
    networks:
      - frontend_net

networks:
  spring_net:
  frontend_net: